version: '3.11'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
      - db

  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh", "-c", "pg_isready" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/frontend
    stdin_open: true
    tty: true
    command: npm run dev
    depends_on:
      - backend
    networks:
      - frontend

volumes:
    postgres_data: {}

networks:
  backend:
  db:
  frontend: